title: "caizhiyuannn.github.io"
description: "nothing to say.. @caizhiyuannn@gmail.com"
theme: jekyll-theme-modernist

baseurl: ''

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "posts"
      author: "caizhiyuannn"
